#!/bin/bash
# Script to display all active IPv4 IPs on the machine

# Use ifconfig to get network interface information and extract IPv4 addresses
ifconfig | grep -oP 'inet \K[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | sort -V
