#!/bin/bash
# Script that listens on port 98 on localhost and displays received data

# Use netcat (nc) to listen on localhost port 98
# -l: listen mode
# -p: specify port (some versions use this flag)
# 127.0.0.1: bind to localhost only
# 98: port number
nc -l 127.0.0.1 98
